# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
configHash: "1" # configuration change detection
codenow:
  instance: ""
  applicationName: ""
  applicationRuntimeName: ""
  applicationVersion: ""
  componentRuntimeName: "java-maven"
  componentName: "java-maven"
  componentVersion: ${project.version}
  templateId: ""
  domainName: "omi-dev.stxcn.codenow.com"
  environmentId: ""

buildNumber: "${env.BUILD_NUMBER}"

image:
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  externalEndpointEnabled: true

configFiles: {}
environmentVariables: {}

fluentbit:
  istioProxy:
    enabled: true
    parser: envoy-logging-filter-parser
  parser: oxus-app-component-json

metricsPrometheusEnabled: false
metricsPrometheusStep: PT1M

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
